### ISSUE TITLE
Allowed to post without content

### ISSUE THREAD

**Issue by michaelfransen** [hartlco/Icro#10]
## Background

This is a very small bug. Currently the app allows you to post even though you haven't entered any content. A post actually isn't created though.

## Proposal

Disable the Post button and make the font grey until content is entered. If all content is removed it should go back to the grey/disabled state. 

I am willing to make this change, but I wanted to run it by people before doing it.

**Comment by hartlco** [comment]
@michaelfransen I would welcome this change! It's clearly a bug that should be fixed.
