### ISSUE TITLE
Loading/Error Message does not wrap

### ISSUE THREAD

**Issue by sauberfred** [hartlco/Icro#19]
I found this to be a problem with the german translations of the error messages as they are a bit longer. But this should also be a problem on smaller screens and if the user is using display zoom.

The statusLine layout from SwiftMessages is not supposed to warp, see https://github.com/SwiftKickMobile/SwiftMessages/issues/193.
As mentioned in the issue one could modify the xib file or use a different layout.

**Comment by Leon-Watschengaun** [comment]
Darn, sorry, forgot the name of the program who runs this issues.
It is free, just google it, but it takes about 15 min to run through whole function based library.
Sure you will solve it and just have one request don't use ` bodyLabel` , some people may find it offensive. 
Mwah

**Comment by TimothyBergher** [comment]
I agree with Leon, you really shouldn't use 'bodyLabel' as it is a mildly ableist term. Please replace with something more inclusive.

**Comment by hartlco** [comment]
This issue was addressed when I replaced SwiftMesages with my own implementation:

![Simulator Screen Shot - iPhone 8 - 2019-12-31 at 07 48 32](https://user-images.githubusercontent.com/1497750/71612688-50e36e80-2ba2-11ea-9896-00bb7ac6f788.png)
