### ISSUE TITLE
Prepare App for different localisations

### ISSUE THREAD

**Issue by hartlco** [hartlco/Icro#3]
Currently all strings are hardcoded. Those meed to be migrated to .strings files in order to be ready for more languages.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sauberfred** [comment]
I started working on this. Being new to iOS development i have no idea if i did it correctly.
I am not yet completely done but pushed my progress to my fork https://github.com/hartlco/Icro/compare/master...sauberfred:master.
Should i create a pull request or wait until i am done?

**Comment by hartlco** [comment]
@sauberfred In general I prefer it to have pull-requests with features/improvements you consider as `Done`. Let me know if you are stuck somewhere or need guidance.
I just quickly checked your current state. It's usual good practice to have the keys for your localisations descriptive and noticeable if not translated. 
So instead of:
```
"Add" = "Hinzufügen";
```

have somethings like this:

```
"BLACKLISTVIEWCONTROLLER_ADDBUTTON_TITLE" = "Hinzufügen";
```

Here untranslated keys will pop up immediately and also give context for the translation itself.

**Comment by sauberfred** [comment]
@hartlco i think i am done. I used descriptive keys as you suggested.
I did not include the german translation as i think this should be done in its one pull-request.

**Comment by hartlco** [comment]
#8 is merged. Closing here!
