### ISSUE TITLE
Keyboard hiding after each letter, Adding a micropub end point does not seem to work

### ISSUE THREAD

**Issue by bmann** [hartlco/Icro#58]
First -- thanks for this app! Looks really great, it's awesome that you've open sourced it, and it was great to see general Micropub support in there as well.

I downloaded this morning on iOS. When trying to type letters into any of the fields of the Post to Micropub section, after each typed letter, the iOS keyboard hides itself. So I have to click into the field again, type one more letter, and then the keyboard slides down.

I copy/pasted my blog IndieAuth end point to get it filled in, and clicked on IndieAuth. It successfully auth'd with my end point, and re-opened Icro, but the endpoint URL and Access token were not filled in.

Not sure what to try next -- I _assume_ what is supposed to happen, is that the endpoint and token were supposed to auto-populate from the Indie Auth.

**Comment by hartlco** [comment]
Hey @bmann, thank you for opening the issue. I just started working on the keyboard dismissal problem.

Regarding the auto-fill issue:
The URL-Scheme should auto-fill the access token, you are then supposed to manually enter the micropub endpoint above the access token. I know, this isn’t explained at all and needs to be addressed.
As you mentioned, the access token is not auto-filled. Are you using a homebrew solution for micropub or connected to a CMS like Wordpress?

**Comment by hartlco** [comment]
I briefly looked into it and submitted a new TestFlight build addressing the access token issue.
The token does not get populated from indie-auth if the micropub endpoint URL is not filled already.
You can work around the issue in the current build by filling out your micropub endpoint URL and then starting the indieauth flow. In the upcoming Testflight, this issue should be resolved.

**Comment by bmann** [comment]
I’m using Voxpelli’s Micropub server https://github.com/voxpelli/webpage-micropub-to-github

IndieKit is probably what I’m going to switch to because it supports media uploads. 

Happy to help test / support / document for others. Will try it and report back.

**Comment by bmann** [comment]
Got the auth token filled in with the end point listed. Thanks!

**Comment by hartlco** [comment]
Good to hear. Did you already try if posting works?
If yes, I would close this issue.

**Comment by bmann** [comment]
It did not post, but it may be on my end. Let’s close this one. I’ll open a new one with full details if it’s an issue still.
