### ISSUE TITLE
Swipe gestures in conversation view

### ISSUE THREAD

**Issue by donnywdavis** [hartlco/Icro#61]
This is more just odd behavior to me than an issue. Was testing out the swipe gestures that were just added back in the latest beta and noticed that while in conversation view you could still swipe left to open the same conversation view. Not sure how many people will actually do this but could lead to some confusion if they do and then have to swipe back multiple times to get out of conversation view. Also same with the context menu. 

Feels that the conversation view could be deactivated for both of those options while on the conversation view. Not sure how easy that is since I haven't worked with context menus yet. But just some feedback I wanted to share. 🙂

**Comment by hartlco** [comment]
In the most recent commit I disabled the chat context menus if a chat is shown.
I'm still leaving the `reply` option as it helps with pre-populating the username in the compose text field.

Thank you for reporting the issue!
