### ISSUE TITLE
Show loading state in "Load more" cell

### ISSUE THREAD

**Issue by hartlco** [hartlco/Icro#64]
After tapping `Load more` indicate the action is ongoing. Disable the button and show an indicator inside the cell.

**Comment by Dejal** [comment]
Also experiment with automatically loading when reaching the top or bottom of loaded posts. Can simply display a bar with an activity indicator and "Loading..." message.

**Comment by Dejal** [comment]
In dark mode, the disabled loading text pretty much disappears.
