### ISSUE TITLE
Swiping the ProfileTableViewCell left or right crashes Icro

### ISSUE THREAD

**Issue by sauberfred** [hartlco/Icro#9]
If you try to swipe the ProfileCell in the Profile tab either to the right or left side Icro crashes with an "Index out of range" Error in the `item` function of ListViewModel. 

    func item(for index: Int) -> Item {
        return items[index]
    }

This happens in the Simulator and on my iPhone 6s.

**Comment by sauberfred** [comment]
Ok it only crashes if the user has zero post/replies. If one has some swiping the ProfileCell shows the quick actions ![GitHawk Upload by sauberfred](https://i.imgur.com/SfiPzPx.jpg) Choosing e.g. Reply the first item in the post/replies list is used as reference.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hartlco** [comment]
Swiping the header cell should be disabled anyway. I treat this as a bug :)

**Comment by michaelfransen** [comment]
@sauberfred Do you want to fix this? If not, I can take a look.

**Comment by sauberfred** [comment]
@michaelfransen as i am not sure how to fix it, feel free to look into it.
